# Generated by Django 4.0.5 on 2022-06-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='open_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
